dish_mappings = {
    #Pulse, oil, turmeri, chilli, potato, soy meat
    # - khichuri (pulse,rice,oil,onion,chicken)
    "rice cake": ["jaggery", "rice powder"],
    "khichuri": ["rice", "pulse", "onion", "oil"],
    "chocolate roll": ["chocolate", "bread"],
    "dalpuri": ["pea", "garlic", "chilli", "cumin", "turmeric", "onion"],

    "alur dom": ["potato", "onion", "chilli", "turmeric", "oil"],
    
    "shingara": ["potato", "oil", "condiment"],
    "hoch poch": ["pulse", "oil", "turmeric", "chilli", "potato", "soy meat"],
    "hotchpotch": ["pulse", "oil", "turmeric", "chilli", "potato", "soy meat"],
    "bon bun": ["bread", "butter"],
    "murighonto": ["fish", "potato", "turmeric", "chilli", "oil"],
    "biryani": ["rice", "chicken", "ginger", "oil", "condiment", "onion"],
    #Rice, milk, suger, Cinnamon, Cardanom 
    "kheer": ["rice", "milk", "sugar", "cinnamon", "cardamom"],
    "chotpoti": ["chilli", "cucumber", "potato", "chickpea"],
    "somucha": ["meat", "onion", "flour", "oil", "peas", "chilli", "coriander leaves"],
    "chips": ["potato", "oil"],
    "pulse pakoda": ["pulse", "onion", "green chilli", "cumin seeds", "oil"],
    "fish egg pakoda": ["fish egg", "pulse", "onion", "green chilli", "cumin seeds", "oil"],
    "pakoda": ["pulse", "onion", "green chilli", "cumin seeds", "oil"],
    "pakora": ["pulse", "onion", "green chilli", "cumin seeds", "oil"],
    "smoothie": ["banana", "mango", "milk"],
    "halua": ["semolina", "nutmeg", "jaggery", "nut", "ghee"],
    "halwa": ["semolina", "nutmeg", "jaggery", "nut", "ghee"],
    "halim": ["beef", "coriander seeds", "onion", "chilli"],
    #flour, potato, salt, oil, chilli, turmeric)	
    "vegetable bun": ["potato", "salt", "oil", "chilli", "tumeric", "bread"],
    "pulao": ["rice", "oil", "bay leaves", "cinnamon", "garlic", "onion", "butter"],
    "polau": ["rice", "oil", "bay leaves", "cinnamon", "garlic", "onion", "butter"],
    "vegetable polau": ["rice","potato", "pulse", "oil", "bay leaves", "cinnamon", "garlic", "onion", "butter"],
    "nimki": ["flour", "butter", "salt", "oil", "mustard seeds"],
    "snack": ["sugar", "rice", "coconut"],
    "egg cake": ["egg", "flour", "sugar"],
    "ice cream": ["milk", "cream", "sugar"],
    "luchi": ["flour", "ghee", "oil", "water"],
    "jalebi": ["flour", "tumeric", "curd", "water"],
    "omlet": ["eggs", "butter", "oil", "salt", "pepper"],
    "soan papdi": ["flour", "ghee", "sugar", "milk"],
    "sandesh": ["cottage cheese", "sugar", "flour"],
    "cheese curds": ["cheese", "milk", "lemon", "sugar"],
    "mango morabba": ["mango", "sugar", "chilli"],
    "mango bar": ["mango", "sugar", "water"],
    "chanachur": ["chickpea", "puffed rice", "chilli", "oil", "onion"],
    "paratha": ["flour", "water", "salt", "oil"],
    "porota": ["flour", "water", "salt", "oil"],
    "chilibread": ["bread", "chilli"],
    "plum cake": ["plum", "sugar", "flour"],
    "puffed rice mix": ["coconut", "sugar", "milk", "puffed rice"],
    "tropicana fruits": ["banana", "mango"],
    "fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "meni fish curry": ["meni fish", "potato", "onion", "chilli", "turmeric"],
    "big fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
     "fish egg curry": ["fish egg", "potato", "onion", "chilli", "turmeric"],
    "soy meat curry": ["soy meat", "potato", "onion", "chilli", "turmeric"],
    "shrimp fish curry": ["shrimp", "fish", "potato", "onion", "chilli", "turmeric"],
    "tilipia fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "puffed rice balls": ["puffed rice", "jaggery", "water", "mustard oil"],
    "crunchy puffed rice balls": ["puffed rice", "jaggery", "water", "mustard oil"],
    "crispy flettened rice balls": ["puffed rice", "jaggery", "water", "mustard oil"],
    "puffed rice bowl": ["puffed rice", "jaggery", "water", "mustard oil"],
    "swamp barb curry": ["swamp barb", "potato", "onion", "chilli", "turmeric"],
    "shrimp curry": ["shrimp", "potato", "onion", "chilli", "turmeric"],
    "sour": ["shrimp", "potato", "onion", "chilli", "turmeric"],
    "sauce": ["water", "salt"],
    "prashad": ["ghee", "flour", "sugar"],
    "proshad": ["ghee", "flour", "sugar"],
    "meat curry": ["meat", "potato", "onion", "chilli", "turmeric"],
    "beef curry": ["beef", "potato", "onion", "chilli", "turmeric"],
    "poultry meat curry": ["chicken", "potato", "onion", "chilli", "turmeric"],
    "prawn curry": ["prawn", "potato", "onion", "chilli", "turmeric"],
    "hilsha fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "flat bread": ["flour", "water", "salt"],
    "flattened rice laddu": ["flattened rice", "jaggery", "ghee", "cardamom"],
    "tandoori bread": ["flour", "water", "salt"],
    "dried fish smash": ["dried fish", "chilli", "onion", "mustard oil"],
    "dried fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "hilsha fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "small fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "mughalai": ["chicken", "onion", "garlic", "fenugreek leaves", "spices"],
    "mughali": ["chicken", "onion", "garlic", "ginger", "chilli"],
    "duck curry": ["duck", "potato", "onion", "chilli", "turmeric"],
    #fish bhuna (onion,green chili,tomato,coriander leaves,soyabean oil)	
    "fish bhuna": ["onion", "fish", "green chilli", "tomato", "coriander leaves", "soybean oil"],
    "tomato bhuna": ["onion", "green chilli", "tomato", "coriander leaves", "soybean oil"],
    "pulse bhuna": ["onion", "green chilli", "pulse", "coriander leaves", "soybean oil"],
    "hilsha fish bhuna": ["onion", "fish", "green chilli", "tomato", "coriander leaves", "soybean oil"],
    "potato curry": ["potato", "chilli", "tumeric", "onion", "mustard oil"],
    "brinjal curry": ["brinjal", "chilli", "tumeric", "onion", "mustard oil"],
    "bean curry": ["bean", "chilli", "tumeric", "onion", "mustard oil"],
    "tomato curry": ["tomato", "chilli", "tumeric", "onion", "mustard oil"],
    "bitter melon curry": ["bitter melon", "chilli", "tumeric", "onion", "mustard oil"],
    "pointed gourd curry": ["pointed gourd", "chilli", "tumeric", "onion", "mustard oil"],
    "bottle gourd leaf curry": ["bottle gourd", "chilli", "tumeric", "onion", "mustard oil"],
    "bottle gourd curry": ["bottle gourd", "chilli", "tumeric", "onion", "mustard oil"],
    "gourd curry": ["bottle gourd", "chilli", "tumeric", "onion", "mustard oil"],
    "ash gourd curry": ["ash gourd", "chilli", "tumeric", "onion", "mustard oil"],
    "pulse curry": ["pulse", "chilli", "tumeric", "onion", "mustard oil"],
    "okra curry": ["okra", "chilli", "tumeric", "onion", "mustard oil"],
    "cucurbit curry": ["cucurbit", "chilli", "tumeric", "onion", "mustard oil"],
    "raddish curry": ["raddish", "chilli", "tumeric", "onion", "mustard oil"],			
    "fried dal": ["pigeonpea", "onion", "tomato", "chilli", "tumeric"],
    "jamai pitha": ["powdered rice", "jaggery", "coconut", "sugar"],
    "bhapa pitha": ["powdered rice", "jaggery", "coconut", "sugar"],
    "vapa pitha": ["powdered rice", "jaggery", "coconut", "sugar"],
    "chitoi pitha": ["powdered rice", "jaggery", "coconut", "sugar"],
    "jamai pitha": ["powdered rice", "jaggery", "coconut"],
    "papaya curry": ["papaya", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    #pulse chop (pulse, water lilly, chilli, soybean oil)	
    "pulse chop": ["pulse", "water lilly", "chilli", "soybean oil"],
    "palm chop": ["palm", "water lilly", "chilli", "soybean oil"],
    "radish chop": ["radish", "water lilly", "chilli", "soybean oil"],
    "tumeric pulse chop": ["tumeric", "pulse", "water lilly", "chilli", "soybean oil"],
    "potato vegetable": ["potato", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "fish vegetable": ["fish", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "bitter gourd vegetable": ["bitter gourd", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "papaya vegetable": ["papaya", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "pulse vegetable": ["pulse", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "raddish vegetable": ["raddish", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "smashed potato": ["beef", "potato", "onion", "tumeric", "oil", "chilli"],
    "smashed dried fish": ["fish", "potato", "onion", "tumeric", "oil", "chilli"],
    "mashed dried fish": ["fish", "potato", "onion", "tumeric", "oil", "chilli"],
    "mashed item": ["fish", "potato", "onion", "tumeric", "oil", "chilli"],
    "mango fruit drink": ["mango", "water", "sugar"],
    "mango drink": ["mango", "water", "sugar"],
    
    "smashed fish": ["fish", "potato", "onion", "tumeric", "oil", "chilli"],
    "smashed chilli": ["chilli", "coriander leaves", "onion"],
    "smashed brinjal": ["chilli", "coriander leaves", "brinjal", "oil"],
    "smashed olive": ["chilli", "coriander leaves", "olive", "oil"],
    "smashed bean": ["chilli", "coriander leaves", "bean", "oil"],
    "smashed hyacinth bean": ["chilli", "coriander leaves", "hyacinth bean", "oil"],
    "smashed taro root": ["chilli", "coriander leaves", "taro", "oil"],
    "smashed stolon of taro": ["chilli", "coriander leaves", "taro", "oil"],
    "smashed gram": ["chilli", "coriander leaves", "gram", "oil"],
    "smashed vegetable": ["chilli", "coriander leaves", "potato", "gram", "oil"],
    "smashed elephant apple": ["chilli", "coriander leaves", "elephant apple", "oil"],
    "smashed pulse": ["chilli", "coriander leaves", "pulse", "oil"],
    "smashed banana": ["chilli", "coriander leaves", "banana", "oil"],
    "nut smash": ["chilli", "coriander leaves", "nut", "oil"],
    "mashed unripe banana": ["chilli", "coriander leaves", "banana", "oil"],
    "smashed pointed gourd": ["chilli", "coriander leaves", "pointed gourd", "oil"],
    "smashed shrimp": ["shrimp", "potato", "onion", "tumeric", "oil", "chilli"],
    "fried smashed potato": ["potato", "onion", "tumeric", "oil", "chilli"],
    "fried smashed pulse": ["pulse", "potato", "onion", "tumeric", "oil", "chilli"],
    #lentil fritters (onion, coriander leaves, lentil, ginger, garlic, chili, oil)	
    "lentil fritters": ["onion", "coriander leaves", "ginger", "garlic", "chilli", "oil", "lentils"],
    "peyaju": ["onion", "coriander leaves", "ginger", "garlic", "chilli", "oil", "lentils"],
    "piaju": ["onion", "coriander leaves", "ginger", "garlic", "chilli", "oil", "lentils"],
    "fruits": ["orange", "apple"],
    "burger": ["bread", "meat"],
    "chicken burger": ["bread", "chicken"],
    "fried egg": ["egg", "oil", "green chilli"],
    "roast egg": ["egg", "oil", "green chilli"],
    "fried chicken": ["chicken", "oil", "green chilli"],
    "fried cucurbit": ["cucurbit", "oil", "green chilli"],
    "fuska": ["potato", "chickpea", "chilli", "tamarind", "onion", "oil"],
    "tamarind pickle": ["tamarind", "chilli", "salt", "oil", "cumin"],
    "pickle of elephant apple": ["elephant apple", "chilli", "salt", "oil", "cumin"],
    "elephant apple pickle": ["elephant apple", "chilli", "salt", "oil", "cumin"],
    "fuchka": ["potato", "chickpea", "chilli", "tamarind", "onion", "oil"],
    "fried pumpkin flower": ["pumpkin flower", "oil", "green chilli"],
    "fried cauliflower": ["cauliflower", "oil", "green chilli"],
    "fried vegetable": ["bean", "potato", "oil", "green chili"],
    "fried tomato": ["tomato", "oil", "green chilli"],
    "fried chickpeas": ["chickpeas", "oil", "green chilli"],
    "chickpea fry": ["chickpeas", "oil", "green chilli"],
    "pigeon pea fry": ["pigeonpea", "oil", "green chilli"],
    "fry": ["potato", "oil", "green chilli"],
    "fried tomato": ["tomato", "oil", "green chilli"],
    "fried bean": ["tombeanato", "oil", "green chilli"],
    "fried raddish": ["raddish", "oil", "green chilli"],
    "fried telpaia fish": ["tilipia", "oil", "green chilli"],
    "garam masala": ["cumin", "coriander", "pepper"],
    "cabbage curry": ["cabbage", "chilli", "tumeric", "onion", "oil"],
    "carrot curry": ["carrot", "chilli", "tumeric", "onion", "oil"],
    "cucumber curry": ["cucumber", "chilli", "tumeric", "onion", "oil"],
    "cauliflower curry": ["cauliflower", "chilli", "tumeric", "onion", "oil"],
    "potato chops": ["potato", "onion", "green chilli", "oil"],
    "brinjal chop": ["brinjal", "onion", "green chilli", "oil"],
    "chop": ["potato", "onion", "green chilli", "oil"],
    "vegetable leaf chop": ["vegetable leaf", "onion", "green chilli", "oil"],
    "cauliflower chops": ["cauliflower", "onion", "green chilli", "oil"],
    "fish chop": ["fish", "onion", "green chilli", "oil"],
    "cabbage chop": ["cabbage", "onion", "green chilli", "oil"],
    "chicken soup": ["chicken", "oil", "chilli", "tumeric", "coriander leaf"],
    "meat soup": ["meat", "oil", "chilli", "tumeric", "coriander leaf"],
    "meat broth": ["meat", "oil", "chilli", "tumeric", "coriander leaf"],
    "egg broth": ["egg", "oil", "chilli", "tumeric", "coriander leaf"],
    "broth of meat": ["meat", "oil", "chilli", "tumeric", "coriander leaf"],
    "fish broth": ["fish", "oil", "chilli", "tumeric", "coriander leaf"],
    "potato soup": ["potato", "oil", "chilli", "tumeric", "coriander leaf"],
    "soup": ["potato", "oil", "chilli", "tumeric", "coriander leaf"],
    "vegetable soup": ["potato", "oil", "chilli", "tumeric", "coriander leaf"],
    "rasmalai": ["milk", "sugar", "pistachio", "curd"],
    "rasaw malai": ["milk", "sugar", "pistachio", "curd"],
    "danish": ["bread", "cream", "butter"],
    "meat+potato": ["meat", "potato"],
    "vegetable fry": ["potato", "pulse", "onion", "chilli", "oil"],
    "potato fry": ["potato", "onion", "chilli", "oil"],
    "tomato fry": ["tomato", "onion", "chilli", "oil"],
    "bean fry": ["bean", "onion", "chilli", "oil"],
     "pumpkin fry": ["pumpkin", "onion", "chilli", "oil"],
    "pulse fry": ["pulse", "onion", "chilli", "oil"],
    "pea seed fry": ["pea", "onion", "chilli", "oil"],
    "raddish fry": ["raddish", "onion", "chilli", "oil"],
    "fried potato": ["potato", "onion", "chilli", "oil"],
    "cauliflower fry": ["cauliflower", "onion", "chilli", "oil"],
    "brinjal fry": ["brinjal", "onion", "chilli", "oil"],
    "bringle fry": ["brinjal", "onion", "chilli", "oil"],
    "salt brinjal fry": ["brinjal", "onion", "chilli", "oil"],
    "shrimp fry": ["shrimp", "onion", "chilli", "oil"],
    "onion fry": ["onion", "chilli", "oil"],
     "fried potato": ["potato", "onion", "chilli", "oil"],
    "mix fry": ["chicken", "potato", "pointed gourd", "oil", "pulse"],
    "egg fry": ["egg", "tomato", "green chilli", "onion", "tumeric", "oil"],
    "pointed gourd fry": ["pointed gourd", "onion", "oil"],
    "spine gourd fry": ["spine gourd", "onion", "oil"],
    "bottle gourd flower fry": ["bottle gourd", "onion", "oil"],
    "mixed vegetables": ["radish," "onion", "potato", "carrot", "oil"],
    "fried vegetables": ["radish," "onion", "potato", "carrot", "oil"],
    "tip vegetables": ["eggplant", "potato", "radish", "spinach"],
    "vegetable": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric"],
    "vegetbles": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric"],
    "vegetable curry": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric", "bean"],
    
    "vegetable leaf curry": ["potato", "vegetable leaf", "taro", "salt", "soybean oil", "chilli", "tumeric", "bean"],
    "vegetable curry mix": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric", "bean"],
    "vegetable fry": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric", "bean"],
    "egg curry": ["egg", "potato", "onion", "spice", "tumeric", "chilli", "salt"],
	"fried peas": ["peas", "coriander leaves", "chilli", "oil"],
    "fried pea seeds": ["peas", "coriander leaves", "chilli", "oil"],
    "naru": ["coconut", "jaggery", "sugar"],
    "samosas": ["potatos", "carrots", "onion", "oil", "green chilli"],
    "salad": ["tomato", "cucumber", "onion", "radish", "ginger"],
    "papaya salad": ["papaya", "cucumber", "onion", "radish", "ginger"],
    "tomato salad": ["tomato", "cucumber", "onion", "radish", "ginger"],
    "tomato oil": ["tomato", "oil"],
    "condiment": ["green chilli", "coriander"],
    "mixed condiment": ["green chilli", "coriander"],
    "jhalmuri": ["rice puffs", "potato", "tomato", "onion", "oil"],
    "pitha": ["milk", "rice powder", "jaggery", "payesh"],
    "pitha - pati sapta": ["rice flour", "sugar", "milk"],
    "water lilly fry": ["black cumin", "soybean oil", "onion", "water lily", "chilli"],
    "water lilly curry": ["black cumin", "soybean oil", "onion", "water lily", "chilli"],
    "fried brinjal": ["brinjal", "chilli", "oil", "onion"],
    "fried pulse": ["pulse", "chilli", "oil", "onion"],
    "fried bittermelon": ["bitter melon", "tumeric", "chilli", "oil"],
    "fish fries": ["fish", "onion", "oil", "chilli", "coriander leaves"],
    "pulse fries": ["pulse", "onion", "oil", "chilli", "coriander leaves"],	
    "fried cabbage": ["cabbage", "chilli", "oil", "coriander leaves"],
    "fried ladis fingers": ["ladis fingers", "chilli", "oil", "onion"],
    #chicken biryani (cucumber, lemon, chilli)			
    "chicken biryani": ["chicken", "lemon", "chilli", "onion", "cucumber"],
    "fried rice": ["rice", "egg", "onion", "oil"],
    "fried puffed rice": ["puffed rice", "egg", "onion", "oil"],
    "fried fish": ["oil", "hilsha", "salt", "chilli", "coriander leaves"],
    "fried rui fish": ["oil", "rohu", "salt", "chilli", "coriander leaves"],
    "fried small fish": ["oil", "hilsha", "salt", "chilli", "coriander leaves"],
    "hilsha fish fry": ["oil", "hilsha", "salt", "chilli", "onion"],
    "fried hilsha fish": ["oil", "hilsha", "salt", "chilli", "coriander leaves"],
    "curry": ["turmeric", "chilli", "salt", "coriander leaves", "potato", "onion", "hilsha"],
    "chutney": ["jujube", "chilli", "salt", "mustard oil"],
    "sukto": ["bitter gourd", "banana", "eggplant", "potato"],

}