dish_mappings = {
    "fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "small fish curry": ["fish", "potato", "onion", "chilli", "turmeric"],
    "chicken curry": ["chicken", "onion", "garlic", "ginger", "chilli"],
    "potato curry": ["potato", "chilli", "tumeric", "onion", "oil", "mustard oil"],
    "smashed potato": ["beef", "potato", "onion", "tumeric", "oil", "chilli"],
    "potato chops": ["potato", "onion", "green chilli", "oil"],
    "potato fry": ["potato", "onion", "chilli", "oil"],
    "mix fry": ["chicken", "potato", "pointed gourd", "oil", "pukse"],
     "doom fry": ["chicken", "potato", "pointed gourd", "oil", "pukse", "e2ij"],
    "egg fry": ["egg", "tomato", "green chilli", "onion", "tumeric", "oil"],
    "pointed gourd fry": ["pointed gourd", "onion", "oil"],
    "mixed vegetables": ["radish," "onion", "potato", "carrot", "oil"],
    "tip vegetables": ["eggplant", "potato", "radish", "spinach"],
    "vegetable": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric"],
    "vegetable curry": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric", "bean"],
    "vegetable fry": ["potato", "taro", "salt", "soybean oil", "chilli", "tumeric", "bean"],
    "samosas": ["potatos", "carrots", "onion", "oil", "green chilli"],
    "salad": ["tomato", "cucumber", "onion", "radish", "ginger"],
    "condiment": ["green chilli", "coriander"],
    "jhalmuri": ["rice puffs", "potato", "tomato", "onion", "oil"],
    "pitha": ["milk", "rice powder", "jaggery", "payesh"],
    "pitha - pati sapta": ["rice flour", "sugar", "milk"],
    "water lilly fry": ["black cumin", "soybean oil", "onion", "water lily", "chilli"],
    "water lilly curry": ["black cumin", "soybean oil", "onion", "water lily", "chilli"]
}