food_mappings = {
    "fish egg": "Fish roe, cooked",
    "elephant apple": "Elephant apple, ripe, raw",
    "spine gourd": "Gourd, teasle, boiled* (without salt)",
    "spicy puffed rice": "Rice, puffed, salted",
    "spiced puffed": "Rice, puffed, salted",
    "jhal": "Rice, puffed, salted",
    "rice puffs": "Rice, puffed, salted",
    "popped rice": "Rice, popped",
    "Rice pops": "Rice, popped",
    "flattened rice": "Rice flaked",
    "flaked rice": "Rice flaked",
    "rice powder": "Rice flaked",
    "rice flakes": "Rice flakes, white grain, water-soaked",
    # General Rice Terms 
    "puffed rice": "Rice, puffed, salted",
    "muri": "Rice, puffed, salted",
    "rice": "Rice, BR-28, boiled* (without salt)",  # Override raw versions with boiled
    "panta": "Rice, BR-28, boiled* (without salt)",  # Override raw versions with boiled
    
    "rice powder": "Rice, BR-28, boiled* (without salt)",
    "boiled rice": "Rice, BR-28, boiled* (without salt)",
    "parboiled rice": "Rice, BR-28, parboiled, milled, raw",
    "white rice": "Rice, white, sunned, polished, milled, boiled* (without salt)",
    "brown rice": "Rice, brown, parboiled, milled, boiled* (without salt)",
    

    "chira": "Rice flakes, white grain, water-soaked",
    # Corn/Maize
    "corn": "Maize/corn, yellow, dried, raw",
    "maize": "Maize/corn, yellow, dried, raw",
    "corn flour": "Maize/corn flour, whole, white",
     "gram flour": "Maize/corn flour, whole, white",
    "maize flour": "Maize/corn flour, whole, white",
    "cornmeal": "Maize/corn, yellow, dried, raw",
    "sweet corn": "Sweet corn, yellow, on the cob, raw",
    "popcorn": "Popcorn, maize (salt added)",
    "barley": "Barley, whole-grain, raw",
    "sweet biscuit": "Biscuit, sweet*",
    "biscuit": "Biscuit, sweet*",
    "hello biscuit": "Biscuit, sweet*",
    "toast biscuit": "Biscuit, sweet*",
    "milk biscuit": "Biscuit, sweet*",
    "danish biscuit": "Biscuit, sweet*",
    "cake": "Biscuit, sweet*",
    "semolina cake": "Biscuit, sweet*",
    "winter cake": "Biscuit, sweet*",
     "bread": "Bread, bun/roll",
     "bun": "Bread, bun/roll",
     "roll": "Bread, bun/roll",
     "loaf of bread": "Bread, bun/roll",
    "bread roll": "Bread, bun/roll",
    "bun": "Bread, bun/roll",
    "white bread": "Bread, white, for toasting",
   "toast": "Bread, white, for toasting",
   "toasted bread": "Bread, white, for toasting",
    # Millets and Sorghum
    "foxtail millet": "Millet, Foxtail, raw",
    "proso millet": "Millet, Proso, whole-grain, raw",
    "millet": "Millet, Proso, whole-grain, raw",  # General millet maps to Proso
    "pear millet": "Pear millet, whole-grain, raw",
    "sorghum": "Sorghum, raw",
    "broomcorn": "Sorghum, raw",
    "Broom corn": "Sorghum, raw",
    # Wheat and Flour
    "wheat": "Wheat, whole, raw",
    "wheat flour": "Wheat, flour, white",
    "chapti": "Wheat, flour, white",
    "flour": "Wheat, flour, white",
    "rice flour": "Wheat, flour, white",
    "white wheat flour": "Wheat flour, white, refined",
    "whole wheat flour": "Wheat flour, brown, whole grain, raw",
    "whole wheat": "Wheat, whole, raw",
    "semolina": "Semolina, wheat, raw",
    "vermicelli": "Vermicelli, boiled* (without salt)",
    "noodles": "Vermicelli, boiled* (without salt)",
    "ruti": "Ruti*",
    "puri": "Ruti*",
    "gourd": "Gourd, bitter, boiled* (without salt)",  # Override raw gourds with best cooked option
    "cucurbit": "Gourd, bitter, boiled* (without salt)",
    "ash gourd": "Gourd, ash, raw",
    "winter melon": "Gourd, ash, raw",
    "bitter gourd": "Gourd, bitter, boiled* (without salt)",
    "bitter melon": "Gourd, bitter, boiled* (without salt)",
    "bottle gourd": "Gourd, bottle, raw",
    "pointed gourd": "Gourd, pointed, boiled* (without salt)",
    "ridge gourd": "Gourd, ridge, raw",
    "snake gourd": "Gourd, snake, raw",
    "sponge gourd": "Gourd, sponge, raw",
    "teasle gourd": "Gourd, teasle, boiled* (without salt)",
   
    "gourd fry": "Gourd, bitter, fry*",  # New addition
    # Vegetables

    "amaranth": "Amaranth, stem, raw",
    "banana stem": "Amaranth, stem, raw",
    "stem amaranth": "Amaranth, stem, raw",
    "vegetable stem": "Amaranth, stem, raw",
    "stem": "Amaranth, stem, raw",
    "scarlet runner bean": "Bean, scarlet runner, raw",
    "beans": "Bean, seeds and pods, raw",
    "snow pea": "Bean, seeds and pods, raw",
    "string beans": "Bean, seeds and pods, raw",
    "hyacinth bean": "Bean, seeds and pods, raw",
    "hyacinth bean seed": "Bean, seeds and pods, raw",
    "hyacinth": "Bean, seeds and pods, raw",
    "beetroot": "Beet root, red, raw",
    "pumpkin flower": "Pumpkin leaves, raw",
    "cucumber leaves": "Pumpkin leaves, raw",
    "brinjal": "Brinjal, purple, long, boiled* (without salt)",
    "bringle": "Brinjal, purple, long, boiled* (without salt)",
    "black brinjal": "Brinjal, purple, long, boiled* (without salt)",
    "eggplant": "Brinjal, purple, long, boiled* (without salt)",  # Eggplant = Brinjal
    "broad beans": "Broad beans, raw",
    "cabbage": "Cabbage, boiled* (without salt)",
    "carrot": "Carrot, boiled* (without salt)",
    "cauliflower": "Cauliflower, boiled* (without salt)",
    "cowpea": "Cowpea, boiled* (without salt)",
    "bora": "Cowpea, boiled* (without salt)",
    "asparagus bean": "Cowpea, boiled* (without salt)",
    "black-eyed pea": "Cowpea, boiled* (without salt)",
    "black eyed pea": "Cowpea, boiled* (without salt)",
    "cucumber": "Cucumber, peeled, raw",
    "pickle": "Cucumber, peeled, raw",
    "drumstick": "Drumstick, pods, raw",
    "moringa": "Drumstick, pods, raw",
    "garlic": "Garlic, raw",
    # Lentils, Grams, and Beans (with alternative names)
    "bengal gram": "Bengal gram, whole, boiled* (without salt)",
    "chickpea": "Bengal gram, whole, boiled* (without salt)",
    "black gram": "Black gram, split, dried, raw",
    "urad beans": "Black gram, split, dried, raw",  # Alternative name for Black Gram
    "green gram": "Green gram, split, boiled* (without salt)",
    "gram": "Green gram, split, boiled* (without salt)",
    "lentil": "Green gram, split, boiled* (without salt)",
    "boiled lentil": "Green gram, split, boiled* (without salt)",
    "pulse": "Green gram, split, boiled* (without salt)",
    "mung beans": "Green gram, split, boiled* (without salt)",  # Alternative name for Green Gram
    "moog pulses": "Green gram, split, boiled* (without salt)",  # Alternative name for Green Gram
    "red gram": "Red gram, split, dried, raw",
    "pigeon pea": "Red gram, split, dried, raw",  # Alternative name for Red Gram
    
    "grass pea": "Grass pea, split, boiled* (without salt)",
    "grampea": "Pea, boiled* (without salt)",
    "pea": "Pea, boiled* (without salt)",
    "soybean": "Soybean, dried, raw",
    "soy meat": "Soybean, dried, raw",
    # Okra & Onions (handling all name variations)
    "okra": "Okra/ladies finger, boiled* (without salt)",
    "ladies finger": "Okra/ladies finger, boiled* (without salt)",
    "lady fingers": "Okra/ladies finger, boiled* (without salt)",
    "ladis finger": "Okra/ladies finger, boiled* (without salt)",
    "ladyfingers": "Okra/ladies finger, boiled* (without salt)",
    "onion": "Onion, raw",
    "papaya": "Papaya, unripe, boiled* (without salt)",
    "green papaya": "Papaya, unripe, boiled* (without salt)",
    "ripe papaya": "Papaya, unripe, boiled* (without salt)",
    "plantain": "Plantain, boiled* (without salt)",
    "pumpkin": "Pumpkin, boiled* (without salt)",
    "raddish": "Radish, boiled* (without salt)",
    "radish": "Radish, boiled* (without salt)",

    "tomato": "Tomato, red, ripe, boiled* (without salt)",
    "tomato ketchup": "Tomato, red, ripe, boiled* (without salt)",
    "tomato sauce": "Tomato, red, ripe, boiled* (without salt)",
    "green tomato": "Tomato, green, raw",
    "turnip": "Turnip, raw",
    "agathi": "Agathi, raw",
    "alligator weed": "Alligator weed, raw",
    "spleen amaranth": "Amaranth, leaves, green, boiled* (without salt)",
    "amaranth leaves": "Amaranth, leaves, green, boiled* (without salt)",
    "bottle gourd leaf": "Amaranth, leaves, green, boiled* (without salt)",
    "red amaranth": "Amaranth, leaves, red, boiled* (without salt)",
    "red amaranth leaves": "Amaranth, leaves, red, boiled* (without salt)",
    "green amaranth leaves": "Amaranth, leaves, green, boiled* (without salt)",
    "dock leaves": "Dock leaves, raw",
    "beet greens": "Beet greens leaves",
    "beet greens leaves": "Beet greens leaves",
    "bengal dayflower": "Bengal dayflower, leaves, raw",
    "dayflower": "Bengal dayflower, leaves, raw",
    "bengal leaves": "Bengal dayflower, leaves, raw",
    "bengal dayflower leaves": "Bengal dayflower, leaves, raw",
    "bitter gourd leaves": "Bitter gourd leaves, green, raw",
    "bottle gourd leaves": "Bottle gourd leaves, raw",
    "bugleweed": "Bugleweed, raw",
    "cassava leaves": "Cassava, leaves, raw",
    "cassia leaf": "Cassava, leaves, raw",
    "colocasia leaves": "Colocasia leaves, green, raw",
    "cowpea leaves": "Cowpea, leaves, raw",
    "dima leaves": "Dima leaves, raw",
    "drumstick leaves": "Drumstick, leaves, raw",
    "fern leaves": "Fern, leaves, raw",
    "fenugreek leaves": "Fenugreek, leaves, raw",

    "malaber spinach": "Indian spinach, boiled* (without salt)",
    "indian spinach": "Indian spinach, boiled* (without salt)",
    "jute leaves": "Jute leaves, raw",
    "pumpkin leaves": "Pumpkin leaves, raw",
    "radish leaf": "Radish leaves, raw",

    "radish leaves": "Radish leaves, raw",
    "slender amaranth leaves": "Slender amaranth leaves, boiled* (without salt)",
    "red spinach": "Spinach, boiled* (without salt)",
    "onion leaves": "Spinach, boiled* (without salt)",
    "spinach": "Spinach, boiled* (without salt)",
    "raddish spinach": "Spinach, boiled* (without salt)",
    "gourd spinach": "Spinach, boiled* (without salt)",
    "taro leaf": "Spinach, boiled* (without salt)",
    "water spinach": "Spinach, boiled* (without salt)",
    "sweet potato leaves": "Sweet potato leaves, raw",
    "potato leaf": "Sweet potato leaves, raw",
    "vegetable potato leaf": "Sweet potato leaves, raw",
    "dark green sweet potato leaves": "Sweet potato leaves, SP4, dark green, mature, raw",
    "light green sweet potato leaves": "Sweet potato leaves, SP8, light green, mature, raw",
    "colocasia": "Colocasia/Taro, boiled* (without salt)",
    "colocasia stem": "Colocasia/Taro, boiled* (without salt)",
    "stolon of taro": "Colocasia/Taro, boiled* (without salt)",
    "taro": "Colocasia/Taro, boiled* (without salt)",
    "elephant plant": "Colocasia/Taro, boiled* (without salt)",
    "taro root": "Colocasia/Taro, boiled* (without salt)",
    "tora root": "Colocasia/Taro, boiled* (without salt)",
    "shabudana": "Colocasia/Taro, boiled* (without salt)",

    "elephant foot": "Elephant foot, corm, boiled* (without salt)",
    "giant taro": "Giant taro, corm, boiled* (without salt)",
    "stolon of taro": "Giant taro, corm, boiled* (without salt)",
    "potato": "Potato, Diamond, boiled* (without salt)",
    "potato mash": "Potato Mash*",
    "sweet potato": "Sweet potato, pale-yellow flesh, boiled* (without salt)",
    "orange sweet potato": "Sweet potato, Komola Sundori, orange flesh, boiled* (without salt)",
    "pale yellow sweet potato": "Sweet potato, pale-yellow flesh, boiled* (without salt)",
    "yellow sweet potato": "Sweet potato, pale-yellow flesh, boiled* (without salt)",
    "purple skin sweet potato": "Sweet potato, skin purple, flesh pale-yellow, boiled* (without salt)",
    "purple skinned sweet potato": "Sweet potato, skin purple, flesh pale-yellow, boiled* (without salt)",
    "purple sweet potato": "Sweet potato, skin purple, flesh pale-yellow, boiled* (without salt)",
    "yam": "Yam, tuber, boiled* (without salt)",
    "white sweet potato": "Sweet potato, white flesh, boiled* (without salt)",
    "white skinned sweet potato": "Sweet potato, white flesh, boiled* (without salt)",
    "cashew": "Cashew nuts, raw",
    "sunflower seeds": "Sunflower seeds, dried",
    "cashew nuts": "Cashew nuts, raw",
    "chilgoza pine": "Chilgoza pine, dried",
    "coconut milk": "Coconut milk",
    "coconut": "Coconut, mature kernel",
    "green coconut": "Coconut, mature kernel",
    "desiccated coconut": "Coconut, desiccated",
    "mashed coconut": "Coconut, desiccated",
    "coconut husk": "Coconut, desiccated",
    "coconut raw sugar": "Coconut, desiccated",
    "nut": "Groundnuts/Peanut, raw",
    "groundnut": "Groundnuts/Peanut, raw",
    "peanut": "Groundnuts/Peanut, raw",
    "jackfruit seeds": "Jackfruit seeds, raw",
    "linseed": "Linseed, raw",
    "lotus seeds": "Lotus seeds, dried",
    "water lily": "Lotus seeds, dried",
    "arum": "Lotus seeds, dried",
    "green lotus seeds": "Lotus seeds, green",
    "mustard seeds": "Mustard seeds, dried",
    "mustard": "Mustard seeds, dried",
    "pistachio": "Pistachio nuts, dried",
    "pumpkin seeds": "Pumpkin seeds, dried",
    "sesame seeds": "Sesame seeds, whole, dried",
    "sesame": "Sesame seeds, whole, dried",
    "walnuts": "Walnuts",
    # Spices & Herbs
    "bay leaf": "Bay leaf, dried",
    "bay leaves": "Bay leaf, dried",
    "indian bay leaves": "Bay leaf, dried",
    "indian bay leaf": "Bay leaf, dried",
    "cardamom": "Cardamom",
    "chilli": "Chilli, red, dry",
    "burned chili": "Chilli, red, dry",
    "dry fried chilli": "Chilli, red, dry",
    "dry chilli": "Chilli, red, dry",
    "chilli powder": "Chilli, red, dry",
    "green chilli": "Chilli, green, with seeds, raw",
    "green pepper": "Chilli, green, with seeds, raw",
    "green paper": "Chilli, green, with seeds, raw",
    "red chilli": "Chilli, red, dry",
    "spices": "Chilli, red, dry",
    "spicy spices": "Chilli, red, dry",
    "dried chilli": "Chilli, red, dry",
    "cinnamon": "Cinnamon, ground",
    "cloves": "Cloves, dried",
    "smashed coriander leaves": "Coriander leaves, raw",
    "coriander leaves": "Coriander leaves, raw",
    "coriander leaf": "Coriander leaves, raw",
    "cilantro": "Coriander leaves, raw",  # Cilantro = Coriander Leaves
    "coriander seed": "Coriander seed, dry",
    "coriander": "Coriander seed, dry",
    "cumin": "Cumin seeds",
    "black seed": "Cumin seeds",
    "black cumin": "Cumin seeds",
    "cumin seeds": "Cumin seeds",
    "fennel": "Fennel seeds",
    "fennel seeds": "Fennel seeds",
    "fenugreek": "Fenugreek seeds",
    "fenugreek seeds": "Fenugreek seeds",
    "ginger": "Ginger root, raw",
    "smashed ginger": "Ginger root, raw",
    "ginger root": "Ginger root, raw",
    "indian pennywort": "Indian pennywort, raw",
    "thankuni leaves": "Indian pennywort, raw",
    "pennywort": "Indian pennywort, raw",
    "lemon grass": "Lemon grass, raw",
    "lemon leaf": "Lemon grass, raw",
    "lemon peel": "Lemon peel, raw",
    "mace": "Mace, ground",
    "nutmeg": "Nutmeg, dried",
    "black pepper": "Pepper, black",
    "black chilli": "Pepper, black",
    "pepper": "Pepper, black",
    "poppy seeds": "Poppy seeds",
    "spearmint leaves": "Spearmint leaves, fresh",
    "spearmint": "Spearmint leaves, fresh",
    "turmeric": "Turmeric, dried",
    "turmeric powder": "Turmeric, dried",
    "termaric": "Turmeric, dried",
    # Fruits
    "apple": "Apple, with skin, raw",
    "apple slices": "Apple, with skin, raw",
    "apple without skin": "Apple, without skin, raw",
    "asian pears": "Asian pears, raw",
    "pears": "Asian pears, raw",
    "anaji kola": "Banana, Sagar, ripe, raw",
    "fruto": "Banana, Sagar, ripe, raw",
    "banana": "Banana, Sagar, ripe, raw",
    "cooking banana": "Banana, Sagar, ripe, raw",
    "unripe banana": "Banana, Sagar, ripe, raw",
    "green banana": "Banana, Sagar, ripe, raw",

    "breadfruit": "Breadfruit, raw",
    "bullocks heart": "Bullocks Heart, ripe, raw",
    "ox heart": "Bullocks Heart, ripe, raw",
    "carambola": "Carambola, raw",
    "star fruit": "Carambola, raw",
    "starfruit": "Carambola, raw",
    "bilimbi": "Carambola, raw",
    "custard apple": "Custard apple, raw",
    "dates": "Dates, dried",
    "raw dates": "Dates, raw",
    
    "emblic": "Emblic, raw",
    "indian gooseberry": "Emblic, raw",
    "gooseberry": "Emblic, raw",
    "amla": "Emblic, raw",
    "amloki": "Emblic, raw",
    "fig": "Fig, ripe, raw",
    "grapes": "Grapes, green, raw",
    "raisin": "Grapes, green, raw",
    "green grapes": "Grapes, green, raw",
    "guava": "Guava, green, raw",
    "hog plum": "Hog plum, raw",
    "plum": "Hog plum, raw",
    "pulm": "Hog plum, raw",
    "jackfruit": "Jackfruit, ripe, raw",
    # Jambolan and its Variants
    "jambolan": "Jambolan, raw",
    "black plum": "Jambolan, raw",
    "java plum": "Jambolan, raw",
    "malabar plum": "Jambolan, raw",
    "jamun": "Jambolan, raw",
    "jaman": "Jambolan, raw",
    "jambul": "Jambolan, raw",
    "jambos": "Jambos, raw",
    "java apple": "Java apple, raw",
    "jujube": "Jujube, raw",
    "jujube fruit": "Jujube, raw",
    "jujuba": "Jujube, raw",
    "lemon": "Lemon, Kagoji, raw",
    "lime": "Lime, sweet, raw",
    "lychee": "Lychee, raw",
    "mango": "Mango, Fazli, orange flesh, ripe, raw",
    "tang": "Mango, Fazli, orange flesh, ripe, raw",
    
    "dry mango": "Mango, Fazli, orange flesh, ripe, raw",
    "dried mango": "Mango, Fazli, orange flesh, ripe, raw",
    "mango fruit leather": "Mango, Fazli, orange flesh, ripe, raw",
    "fazli mango": "Mango, Fazli, orange flesh, ripe, raw",
    "langra mango": "Mango, Langra, yellow flesh, ripe, raw",
    "melon": "Melon, Futi, orange flesh, ripe, raw",
    "monkey-jack": "Monkey-jack, yellowish-orange flesh, raw",
    "monkey jack": "Monkey-jack, yellowish-orange flesh, raw",
    "monkey fruit": "Monkey-jack, yellowish-orange flesh, raw",
    "muskmelon": "Muskmelon, Bangee, light orange flesh, ripe, raw",
    "juice": "Orange juice, raw (unsweetened)",
    "orange juice": "Orange juice, raw (unsweetened)",
    "mango juice": "Orange juice, raw (unsweetened)",
    "orange": "Orange, raw",
    "sweet orange": "Orange, sweet, ripe, raw",
    "blood orange": "Orange, sweet, ripe, raw",
    "malta": "Orange, sweet, ripe, raw",
    "palmyra palm": "Palmyra palm, cotyledon, raw",
    "palmyra palm pulp": "Palmyra palm, pulp, orange flesh, ripe, raw",
    "persimmon": "Persimmon, ripe, raw",
    "pineapple": "Pineapple, ripe, raw",
    "joldugee pineapple": "Pineapple, Joldugee, ripe, raw",
    "pomegranate": "Pomegranate, ripe, with seed, raw",
    "pomelo": "Pomelo, raw",
    "tamarind": "Tamarind, pulp, ripe, raw",
    "tamarind juice": "Tamarind, pulp, ripe, raw",
    "tamarind broth": "Tamarind, pulp, ripe, raw",
    "tamarind soup": "Tamarind, pulp, ripe, raw",
    "tamarind sour": "Tamarind, pulp, ripe, raw",
    "watermelon": "Watermelon, ripe, raw",
    "wood apple": "Wood apple, ripe, raw",
    "stone apple": "Wood apple, ripe, raw",
    "egg": "Egg, chicken, farmed, boiled* (without salt)",  # Override raw with boiled
    "chicken egg": "Egg, chicken, farmed, boiled* (without salt)",
    
    "farmed egg": "Egg, chicken, farmed, boiled* (without salt)",
    "boiled egg": "Egg, chicken, farmed, boiled* (without salt)",
    "boiled chicken egg": "Egg, chicken, farmed, boiled* (without salt)",
    # Native Chicken Eggs
    "native egg": "Egg, chicken, native, boiled* (without salt)",
    "native chicken egg": "Egg, chicken, native, boiled* (without salt)",
    "native boiled egg": "Egg, chicken, native, boiled* (without salt)",
    "native raw egg": "Egg, chicken, native, raw",
    "egg yolk": "Egg, chicken, native, yolk, raw",
    # Duck Eggs
    "duck egg": "Egg, duck, whole, boiled* (without salt)",
    "boiled duck egg": "Egg, duck, whole, boiled* (without salt)",
    "salt": "Salt",
    "black salt": "Salt",
    # Butter & Ghee
    "butter": "Butter, salted",
    "salted butter": "Butter, salted",
    "ghee": "Ghee, cow",  # Default to cow ghee unless specified
    "cow ghee": "Ghee, cow",
    "vegetable ghee": "Ghee, vegetable",
    # Oils
    "oil": "Soybean oil",
    "oil condiment": "Soybean oil",
    "mustard oil": "Mustard oil",
    "palm oil": "Palm oil",
    "peanut oil": "Peanut oil",
    "groundnut oil": "Peanut oil",  # Alternative name
    "sesame oil": "Sesame oil",
    "soybean oil": "Soybean oil",
    "cottonseed oil": "Cottonseed oil",
    "fish oil": "Fish oil, cod liver",
    "cod liver oil": "Fish oil, cod liver",
    # Margarine & Mayonnaise
    "margarine": "Margarine",
    "mayonnaise": "Mayonnaise, salted",
    "salted mayonnaise": "Mayonnaise, salted",
    # Beverages and Drinks
    "coconut water": "Coconut water",
    "green coconut water": "Coconut water",
    "coffee": "Coffee infusion (instant with sugar and milk powder, whole fat)",
    "cold coffee": "Coffee infusion (instant with sugar and milk powder, whole fat)",
    "instant coffee": "Coffee infusion (instant with sugar and milk powder, whole fat)",
    "coffee powder": "Coffee, powder",
    "soft drink": "Soft drinks, carbonated",
    "soda": "Soft drinks, carbonated",
    "carbonated drink": "Soft drinks, carbonated",
    "soy milk": "Soya milk (not sweetened)",
    "soya milk": "Soya milk (not sweetened)",
    "sugarcane juice": "Sugar cane Juice",
    "panela": "Jaggery/Panela, date palm",
    "date": "Jaggery/Panela, date palm",
    "jujube": "Jaggery/Panela, date palm",
    "date palm": "Jaggery/Panela, date palm",
    "palm": "Jaggery/Panela, date palm",
    "palm fruit": "Jaggery/Panela, date palm",
    "date jaggery": "Jaggery/Panela, date palm",
    "red betel leaves": "Betel leaves",
    "vegetable leaf": "Betel leaves",
    "smashed vegetable leaf": "Betel leaves",
    "honey": "Honey",
    "sugar": "Sugar, white",
    "raw sugar": "Sugar, white",
    
    "white sugar": "Sugar, white",
    "jaggery": "Jaggery, sugarcane, solid",
    "sugarcane": "Jaggery, sugarcane, solid",
    "betel leaves": "Betel leaves",
    "leaves": "Betel leaves",
    "neem leaf": "Betel leaves",
    "leaf": "Betel leaves",
    "red betel": "Betel leaves",
    "betel": "Betel leaves",
    "baking powder": "Baking powder",
    "tea": "Tea infusion (with sugar and milk powder, whole fat)",
    "red tea": "Tea infusion (with sugar and milk powder, whole fat)",
    "sweet tea": "Tea, infusion (with sugar)",
    "tea powder": "Tea, powder",
    "drinking water": "Water, drinking",
    "cool drinks": "Water, drinking",
    "water": "Water, drinking",
    # Common Carbonated Drinks
    "drinks": "Water, drinking",
    "cool drinks": "Water, drinking",
    "cola": "Soft drinks, carbonated",
    "coke": "Soft drinks, carbonated",
    "pepsi": "Soft drinks, carbonated",
    "sprite": "Soft drinks, carbonated",
    "7up": "Soft drinks, carbonated",
    "sprite/ 7up": "Soft drinks, carbonated",
    "fanta": "Soft drinks, carbonated",
    "mountain dew": "Soft drinks, carbonated",
    "dr pepper": "Soft drinks, carbonated",
    "root beer": "Soft drinks, carbonated",
    "ginger ale": "Soft drinks, carbonated",
    "club soda": "Soft drinks, carbonated",
    "tonic water": "Soft drinks, carbonated",
    "seltzer": "Soft drinks, carbonated",
    "sparkling water": "Soft drinks, carbonated",
    "energy drink": "Soft drinks, carbonated",
    "red bull": "Soft drinks, carbonated",
    "monster": "Soft drinks, carbonated",
    "mug root beer": "Soft drinks, carbonated",



    
    "buttermilk": "Buttermilk, fluid, low fat",
    "low fat buttermilk": "Buttermilk, fluid, low fat",
    "fluid buttermilk": "Buttermilk, fluid, low fat",

    "cottage cheese": "Cheese, cottage, 25% fat",
    "25% fat cottage cheese": "Cheese, cottage, 25% fat",
    "cheese, cottage": "Cheese, cottage, 25% fat",

    "sweetened curd": "Curd, sweetened, whole milk",
    "cream": "Curd, sweetened, whole milk",
    "curd": "Curd, sweetened, whole milk",
    "whole milk curd": "Curd, sweetened, whole milk",
    "yogurt": "Curd, sweetened, whole milk",

    "buffalo milk": "Milk, buffalo, whole fat",
    "whole fat buffalo milk": "Milk, buffalo, whole fat",

    "skimmed cow milk powder": "Milk, cow, powder, skimmed",
     "horlicks": "Milk, cow, powder, skimmed",
    "cow milk powder": "Milk, cow, powder, skimmed",
    "milk powder": "Milk, cow, powder, skimmed",
    "skimmed milk powder": "Milk, cow, powder, skimmed",

    "whole milk powder": "Milk, cow, powder, whole",
    "cow milk powder whole": "Milk, cow, powder, whole",

    "skimmed cow milk": "Milk, cow, skimmed",
    "skimmed milk": "Milk, cow, skimmed",

    "pasteurized whole cow milk": "Milk, cow, whole fat (pasteurized, UTH)",
    "cow milk": "Milk, cow, whole fat (pasteurized, UTH)",
    "milk": "Milk, cow, whole fat (pasteurized, UTH)",
    "whole cow milk": "Milk, cow, whole fat (pasteurized, UTH)",
    "uth whole milk": "Milk, cow, whole fat (pasteurized, UTH)",

    "condensed sweetened milk": "Milk, cow, whole, condensed, sweetened",
    "condensed cow milk": "Milk, cow, whole, condensed, sweetened",
    "sweetened cow milk": "Milk, cow, whole, condensed, sweetened",
    "sweetened milk": "Milk, cow, whole, condensed, sweetened",
    "whole condensed milk": "Milk, cow, whole, condensed, sweetened",
    "condensed milk": "Milk, cow, whole, condensed, sweetened",

    "goat milk": "Milk, goat, combined breeds",
    "combined breeds goat milk": "Milk, goat, combined breeds",

    "human milk": "Milk, human, mature, raw",
    "mature human milk": "Milk, human, mature, raw",
    "raw human milk": "Milk, human, mature, raw",

    "colostrum": "Milk, human, colostrum, raw",
    "human colostrum": "Milk, human, colostrum, raw",
    "raw colostrum": "Milk, human, colostrum, raw",

    "payesh": "Payesh*",
    "khir": "Payesh*",
    "pasta": "Pasta, cooked, wheat",
    "chicken broth": "Broth, chicken",
    "fruit jelly": "Jelly, fruit",
    "peanut butter": "Peanut butter",
    "chocolate cake": "Chocolate, cake, frosted",
    "dessert": "Chocolate, cake, frosted",
    "chocobean": "Chocolate, dark",
    "chocolate": "Chocolate, dark",
    "drowry milk chocolate": "Chocolate, milk",
    "lollypop": "Sugar, white",
    "crispy chocolate": "Chocolate, dark",
    "sweet": "chocolate, dark",
    "olive": "Olive, ripe",
    "olive pickle": "Olive, pickled",
    "centerfruit": "Chewing gum",
    "chewinggum": "Chewing gum",
    "mango pickle": "Mango, pickled",
    "vinegar": "Vinegar, balsamic",
    "sapodilla": "Sapodilla"
}

