ingredient_categories = {
    # 🥩 Protein
    # 🍗 Protein
    "Anchovy, Gangetic hairfin, dried": "protein",
    "Anchovy, Gangetic hairfin, raw": "protein",
    "Anchovy, Gold spotted grebadier, raw": "protein",
    "Anchovy, Scaly hairfin, raw": "protein",
    "Barb, Olive, raw": "protein",
    "Barb, Olive, without bones, raw": "protein",
    "Barb, Pool barb, eyes included, raw": "protein",
    "Barb, Pool barb, without bones, eyes included, raw": "protein",
    "Bata, raw": "protein",
    "Boal, without bones, raw": "protein",
    "Bronze feather back, raw": "protein",
    "Calbasu, without bones, raw": "protein",
    "Catfish, Bacha, raw": "protein",
    "Catfish, Pabda, raw": "protein",
    "Catla, raw": "protein",


    # 🍗 Protein
    "Beef handi kabab*": "protein",
    "Beef liver, raw": "protein",
    "Beef, meat, lean, boneless, raw": "protein",
    "Beef, meat, 15-20% fat, boneless, raw": "protein",
    "Beef, mince, lean, raw": "protein",
    "Buffalo meat, raw": "protein",
    "Chicken breast, without skin, raw": "protein",
    "Chicken leg, without skin, raw": "protein",
    "Chicken liver, raw": "protein",
    "Duck, meat, raw": "protein",
    "Frog, legs, raw": "protein",
    "Goat meat, lean, raw": "protein",
    "Lamb/mutton, meat, moderately fat, raw": "protein",
    "Lamb/Mutton, liver, raw": "protein",
    "Pigeon meat, raw": "protein",
    "Pork, meat, <5 % fat, raw": "protein",


    # 🥚 Protein
    "Egg, chicken, farmed, raw": "protein",
    "Egg, chicken, farmed, boiled* (without salt)": "protein",
    "Egg, chicken, native, raw": "protein",
    "Egg, chicken, native, boiled* (without salt)": "protein",
    "Egg, chicken, native, yolk, raw": "protein",
    "Egg, duck, whole, raw": "protein",
    "Egg, duck, whole, boiled* (without salt)": "protein",



    # 🍗 Protein
    "Prawn, Monsoon river prawn, raw": "protein",
    "Rohu, river, raw": "protein",
    "Rohu, without bones, raw": "protein",
    "Shrimp, Speckled, raw": "protein",
    "Silver carp, without bones, raw": "protein",
    "Silver needle fish, eyes included, raw": "protein",
    "Spotted snakehead, raw": "protein",
    "Stinging catfish, raw": "protein",
    "Stone roller, raw": "protein",
    "Striped snake-head, raw": "protein",
    "Tilapia, without bones, raw": "protein",
    "Tuna, without bones, raw": "protein",
    "Walking catfish, without bones, raw": "protein",


    # 🍗 Protein
    "Giant river-catfish, raw": "protein",
    "Giant sea perch, whole, dried": "protein",
    "Giant sea perch, without bones, raw": "protein",
    "Goby, Tank goby, raw": "protein",
    "Gourami, Banded gourami, eyes included, raw": "protein",
    "Hilsha, without bones, raw": "protein",
    "Indian river shad, raw": "protein",
    "Indian threadfin, without bones, raw": "protein",
    "Indo-pacific king mackerel, without bones, raw": "protein",
    "Kuria labeo, without bones, raw": "protein",
    "Long-whiskered catfish, without bones, raw": "protein",
    "Mackerel, narrow-barred Spanish, raw": "protein",
    "Minnow, Finescale razorbelly, raw": "protein",
    "Minnow, Finescale razorbelly, dried": "protein",
    "Pangas, without bones, raw": "protein",

    # 🍗 Protein
    "Chanda, Indian glaasy fish, eyes included, raw": "protein",
    "Climbing perch, indigenous, eyes included, raw": "protein",
    "Climbing perch, Thai, without bones, eyes included, raw": "protein",
    "Clown knife fish, without bones, raw": "protein",
    "Common carp, without bones, raw": "protein",
    "Croaker, Black spotted, without bones, raw": "protein",
    "Day's mystus, combined species, eyes included, raw": "protein",
    "Fish ball*": "protein",
    "Fish (Catla, Mrigal, Rohu), dorsal with skin, raw": "protein",
    "Fish (Catla, Mrigal, Rohu), ventral with skin, raw": "protein",
    "Small fish fry*": "protein",
    "Ganges river sprat, combined species, raw": "protein",
    "Gangetic ailia, raw": "protein",
    "Gangetic mystus, raw": "protein",


    # (to be populated)
    # 🥬 Nonprotein
    "Bengal gram, dehulled, split, dried, raw": "nonprotein",
    "Bengal gram, whole, dried, raw": "nonprotein",
    "Bengal gram, whole, boiled* (without salt)": "nonprotein",
    "Black gram, dehulled, dried, raw": "nonprotein",
    "Black gram, split, dried, raw": "nonprotein",
    "Green gram, split, dried, raw": "nonprotein",
    "Green gram, split, boiled* (without salt)": "nonprotein",
    "Green gram, whole, dried, raw": "nonprotein",
    "Grass pea, split, dried, raw": "nonprotein",
    "Grass pea, split, boiled* (without salt)": "nonprotein",
    "Lentil, dried, raw": "nonprotein",
    "Lentil, boiled* (without salt)": "nonprotein",
    "Pea, dried, raw": "nonprotein",
    "Pea, boiled* (without salt)": "nonprotein",
    "Red gram, split, dried, raw": "nonprotein",
    "Soybean, dried, raw": "nonprotein",

    #dairy
    "Buttermilk, fluid, low fat": "nonprotein",
    "Cheese, cottage, 25% fat": "nonprotein",
    "Curd, sweetened, whole milk": "nonprotein",
    "Milk, buffalo, whole fat": "nonprotein",
    "Milk, cow, powder, skimmed": "nonprotein",
    "Milk, cow, powder, whole": "nonprotein",
    "Milk, cow, skimmed": "nonprotein",
    "Milk, cow, whole fat (pasteurized, UTH)": "nonprotein",
    "Milk, cow, whole, condensed, sweetened": "nonprotein",
    "Milk, goat, combined breeds": "nonprotein",
    "Milk, human, colostrum, raw": "nonprotein",
    "Milk, human, mature, raw": "nonprotein",
    "Payesh*": "nonprotein",


# 🥬 Nonprotein? could be spice 
    "Amaranth, stem, raw": "nonprotein",
    "Bean, scarlet runner, raw": "nonprotein",
    "Bean, seeds and pods, raw": "nonprotein",
    "Beet root, red, raw": "nonprotein",
    "Brinjal, purple, long, raw": "nonprotein",
    "Brinjal, purple, long, boiled* (without salt)": "nonprotein",
    "Broad beans, raw": "nonprotein",
    "Cabbage, raw": "nonprotein",
    "Cabbage, boiled* (without salt)": "nonprotein",
    "Carrot, raw": "nonprotein",
    "Carrot, boiled* (without salt)": "nonprotein",
    "Cauliflower, raw": "nonprotein",
    "Cauliflower, boiled* (without salt)": "nonprotein",
    "Chilli, green, with seeds, raw": "nonprotein",
    "Cowpea, pods and seeds, raw": "nonprotein",
    "Cowpea, boiled* (without salt)": "nonprotein",
    "Cucumber, peeled, raw": "nonprotein",

    # 🥬 Nonprotein
    "Drumstick, pods, raw": "nonprotein",
    "Garlic, raw": "nonprotein",
    "Gourd, ash, raw": "nonprotein",
    "Gourd, bitter, raw": "nonprotein",
    "Gourd, bitter, boiled* (without salt)": "nonprotein",
    "Gourd, bitter, fry*": "nonprotein",
    "Gourd, bottle, raw": "nonprotein",
    "Gourd, pointed, raw": "nonprotein",
    "Gourd, pointed, boiled* (without salt)": "nonprotein",
    "Gourd, ridge, raw": "nonprotein",
    "Gourd, snake, raw": "nonprotein",
    "Gourd, sponge, raw": "nonprotein",
    "Gourd, teasle, raw": "nonprotein",
    "Gourd, teasle, boiled* (without salt)": "nonprotein",
    "Okra/ladies finger, raw": "nonprotein",
    # 🥬 Nonprotein
    "Agathi, raw": "nonprotein",
    "Alligator weed, raw": "nonprotein",
    "Amaranth, leaves, spiney, raw": "nonprotein",
    "Amaranth, leaves, red, raw": "nonprotein",
    "Amaranth, leaves, red, boiled* (without salt)": "nonprotein",
    "Amaranth, leaves, green, raw": "nonprotein",
    "Amaranth, leaves, green, boiled* (without salt)": "nonprotein",
    "Dock leaves, raw": "nonprotein",
    "Beet greens leaves": "nonprotein",
    "Bengal dayflower, leaves, raw": "nonprotein",
    "Bitter gourd leaves, green, raw": "nonprotein",
    "Bottle gourd leaves, raw": "nonprotein",
    "Bugleweed, raw": "nonprotein",
    "Cassava, leaves, raw": "nonprotein",
    "Colocasia leaves, black, raw": "nonprotein",

    # 🥬 Nonprotein (grains/vegetables)
    "Rice, BR-28, boiled* (without salt)": "nonprotein",
    "Rice, BR-11, parboiled, milled, raw": "nonprotein",
    "Rice, BR-16, parboiled, milled, raw": "nonprotein",
    "Rice, BR-26, parboiled, milled, raw": "nonprotein",
    "Rice, BR-3, parboiled, milled, raw": "nonprotein",
    "Rice, BRRI Dhan-30, parboiled, milled, raw": "nonprotein",
    "Rice, BRRI Dhan-40, parboiled, milled, raw": "nonprotein",
    "Rice, bran, raw": "nonprotein",
    "Rice, brown, parboiled, home-pounded, raw": "nonprotein",
    "Rice, brown, home-pounded, boiled* (without salt)": "nonprotein",
    "Rice, brown, parboiled, milled, raw": "nonprotein",
    "Rice, brown, parboiled, milled, boiled* (without salt)": "nonprotein",
    "Rice, popped": "nonprotein",
    "Rice, puffed, salted": "nonprotein",
    "Rice, white, sunned, aromatic, raw": "nonprotein",
    "Rice, white, sunned, aromatic, boiled* (without salt)": "nonprotein",

    # 🥬 Nonprotein could be spice 
    "Colocasia leaves, green, raw": "nonprotein",
    "Cowpea, leaves, raw": "nonprotein",
    "Dima leaves, raw": "nonprotein",
    "Drumstick, leaves, raw": "nonprotein",
    "Fern, leaves, raw": "nonprotein",
    "Fenugreek, leaves, raw": "nonprotein",
    "Indian spinach, raw": "nonprotein",
    "Indian spinach, boiled* (without salt)": "nonprotein",
    "Jute leaves, raw": "nonprotein",
    "Pumpkin leaves, raw": "nonprotein",
    "Radish leaves, raw": "nonprotein",
    "Slender amaranth leaves, raw": "nonprotein",
    "Slender amaranth leaves, boiled* (without salt)": "nonprotein",
    "Spinach, raw": "nonprotein",
    "Spinach, boiled* (without salt)": "nonprotein",
    "Sweet potato leaves, raw": "nonprotein",

    # 🥬 Nonprotein could be spice
    "Sweet potato leaves, SP4, dark green, mature, raw": "nonprotein",
    "Sweet potato leaves, SP7, dark green, mature, raw": "nonprotein",
    "Sweet potato leaves, SP8, light green, mature, raw": "nonprotein",
    "Water spinach, raw": "nonprotein",
    "Watercress, raw": "nonprotein",



    # 🥬 Nonprotein could be spice  drinks 
    "Groundnuts/Peanut, raw": "nonprotein",
    "Jackfruit seeds, raw": "nonprotein",
    "Lotus seeds, dried": "nonprotein",
    "Lotus seeds, green": "nonprotein",
    "Coconut milk": "nonprotein",
    "Coconut, desiccated": "nonprotein",
    "Coconut, mature kernel": "nonprotein",
    "Mustard seeds, dried": "nonprotein",

    # 🌶️ Spice (garnish-like seeds/nuts)
    "Sunflower seeds, dried": "garnish",
    "Cashew nuts, raw": "garnish",
    "Chilgoza pine, dried": "garnish",
    "Linseed, raw": "garnish",
    "Pistachio nuts, dried": "garnish",
    "Pumpkin seeds, dried": "garnish",
    "Sesame seeds, whole, dried": "garnish",
    "Walnuts": "garnish",

    # 🧂 Garnish
    "Bay leaf, dried": "garnish",
    "Cardamom": "garnish",
    "Chilli, red, dry": "garnish",
    "Cinnamon, ground": "garnish",
    "Cloves, dried": "garnish",
    "Coriander leaves, raw": "garnish",
    "Coriander seed, dry": "garnish",
    "Cumin seeds": "garnish",
    "Fennel seeds": "garnish",
    "Fenugreek seeds": "garnish",
    "Ginger root, raw": "garnish",
    "Indian pennywort, raw": "garnish",
    "Lemon grass, raw": "garnish",
    "Lemon peel, raw": "garnish",
    "Mace, ground": "garnish",

    # 🧂 Garnish
    "Nutmeg, dried": "garnish",
    "Pepper, black": "garnish",
    "Poppy seeds": "garnish",
    "Spearmint leaves, fresh": "garnish",
    "Turmeric, dried": "garnish",
    "Lemon, Kagoji, raw": "garnish",
    "Lime, sweet, raw": "garnish",
    "salt": "garnish",


    # 🥬 Nonprotein
    "Apple, without skin, raw": "nonprotein",
    "Apple, with skin, raw": "nonprotein",
    "Asian pears, raw": "nonprotein",
    "Banana, Sagar, ripe, raw": "nonprotein",
    "Breadfruit, raw": "nonprotein",
    "Bullocks Heart, ripe, raw": "nonprotein",
    "Carambola, raw": "nonprotein",
    "Custard apple, raw": "nonprotein",
    "Dates, dried": "nonprotein",
    "Dates, raw": "nonprotein",
    "Elephant apple, ripe, raw": "nonprotein",
    "Emblic, raw": "nonprotein",
    "Fig, ripe, raw": "nonprotein",
    "Grapes, green, raw": "nonprotein",
    "Guava, green, raw": "nonprotein",
    "Hog plum, raw": "nonprotein",

    # 🥬 Nonprotein fruit/juice 
    "Orange, raw": "nonprotein",
    "Orange, sweet, ripe, raw": "nonprotein",
    "Palmyra palm, cotyledon, raw": "nonprotein",
    "Palmyra palm, pulp, orange flesh, ripe, raw": "nonprotein",
    "Papaya, ripe, raw": "nonprotein",
    "Persimmon, ripe, raw": "nonprotein",
    "Pineapple, Joldugee, ripe, raw": "nonprotein",
    "Pineapple, ripe, raw": "nonprotein",
    "Pomegranate, ripe, with seed, raw": "nonprotein",
    "Pomelo, raw": "nonprotein",
    "Tamarind, pulp, ripe, raw": "nonprotein",
    "Watermelon, ripe, raw": "nonprotein",
    "Wood apple, ripe, raw": "nonprotein",

    # 🥬 Nonprotein
    "Colocasia/Taro, corm, raw": "nonprotein",
    "Colocasia/Taro, boiled* (without salt)": "nonprotein",
    "Colocasia/Taro/Tannia, cormel, raw": "nonprotein",
    "Colocasia/Taro/Tannia, cormel, boiled* (without salt)": "nonprotein",
    "Elephant foot, corm, raw": "nonprotein",
    "Elephant foot, corm, boiled* (without salt)": "nonprotein",
    "Giant taro, corm, raw": "nonprotein",
    "Giant taro, corm, boiled* (without salt)": "nonprotein",
    "Potato, Diamond, raw": "nonprotein",
    "Potato, Diamond, boiled* (without salt)": "nonprotein",
    "Potato Mash*": "nonprotein",
    "Sweet potato, Komola Sundori, orange flesh, raw": "nonprotein",
    "Sweet potato, Komola Sundori, orange flesh, boiled* (without salt)": "nonprotein",
    "Sweet potato, pale-yellow flesh, raw": "nonprotein",
    "Sweet potato, pale-yellow flesh, boiled* (without salt)": "nonprotein",
    "Sweet potato, skin purple, flesh pale- yellow, raw (without skin)": "nonprotein",

# 🥬 Nonprotein
    "Rice, white, sunned, polished, milled, raw": "nonprotein",
    "Rice, white, sunned, polished, milled, boiled* (without salt)": "nonprotein",
    "Ruti*": "nonprotein",
    "Semolina, wheat, raw": "nonprotein",
    "Sorghum, raw": "nonprotein",
    "Sweet corn, yellow, on the cob, raw": "nonprotein",
    "Vermicelli, wheat, raw": "nonprotein",
    "Vermicelli, boiled* (without salt)": "nonprotein",
    "Wheat flour, brown, whole grain, raw": "nonprotein",
    "Wheat, flour, white": "nonprotein",
    "Wheat flour, white, refined": "nonprotein",
    "Wheat, whole, raw": "nonprotein",
    # 🥬 Nonprotein
    "Jackfruit, ripe, raw": "nonprotein",
    "Jambolan, raw": "nonprotein",
    "Jambos, raw": "nonprotein",
    "Java apple, raw": "nonprotein",
    "Jujube, raw": "nonprotein",
    "Lychee, raw": "nonprotein",
    "Mango, Fazli, orange flesh, ripe, raw": "nonprotein",
    "Mango, Langra, yellow flesh, ripe, raw": "nonprotein",
    "Melon, Futi, orange flesh, ripe, raw": "nonprotein",
    "Monkey-jack, yellowish-orange flesh, raw": "nonprotein",
    "Muskmelon, Bangee, light orange flesh, ripe, raw": "nonprotein",
    "Orange juice, raw (unsweetened)": "nonprotein",

    # 🌶️ Spice
    # (to be added)
    #drinks 
    "Coconut water": "nonprotein",
    "Coffee infusion (instant with sugar and milk powder, whole fat)": "nonprotein",
    "Coffee, powder": "garnish",
    "Soft drinks, carbonated": "nonprotein",
    "Soya milk (not sweetened)": "nonprotein",
    "Sugar cane Juice": "nonprotein",
    "Tea infusion (with sugar and milk powder, whole fat)": "nonprotein",
    "Tea, infusion (with sugar)": "nonprotein",
    "Tea, powder": "garnish",
    "Water, drinking": "nonprotein",


    "Baking powder": "garnish",
    "Betel leaves, raw": "garnish",
    "Honey": "nonprotein",
    "Jaggery, sugarcane, solid": "nonprotein",
    "Jaggery/Panela, date palm": "nonprotein",
    "Jaggery liquid, date palm": "nonprotein",
    "Salt": "garnish",
    "Sugar, white": "nonprotein",

    # 🛢 Oil
    # (to be added)
    #could be garnish 
    "Barley, whole- grain, raw": "nonprotein",
    "Maize/corn flour, whole, white": "nonprotein",
    "Maize/corn, yellow, dried, raw": "nonprotein",
    "Millet, Foxtail, raw": "nonprotein",
    "Millet, Proso, whole-grain, raw": "nonprotein",
    "Rice, BR-28, parboiled, milled, raw": "nonprotein",
    "Rice, white, sunned, aromatic, raw": "nonprotein",
    "Rice, white, sunned, polished, milled, raw": "nonprotein",
    "Sweetcorn, yellow, on the cob, raw": "nonprotein",
    "Wheat, flour, white": "nonprotein",
    "Bengal gram, whole dried, raw": "nonprotein",
    "Green gram, split dried, raw": "nonprotein",
    "Green gram, whole, dried, raw": "nonprotein",
    "Lentil, dried, raw": "nonprotein",
    "Pea, dried, raw": "nonprotein",
    "Red gram, split, dried, raw": "nonprotein",
    "Soybean, dried, raw": "nonprotein",

    "Butter, salted": "oil",
    "Cottonseed oil": "oil",
    "Fish oil, cod liver": "oil",
    "Ghee, cow": "oil",
    "Ghee, vegetable": "oil",
    "Margarine": "oil",
    "Mayonnaise, salted": "garnish",
    "Mustard oil": "oil",
    "Palm oil": "oil",
    "Peanut oil": "oil",
    "Sesame oil": "oil",
    "Soybean oil": "oil",

}
